version: "3"
services:
  app: 
    tty: true
    stdin_open: true
    build:
      context: .
    env_file: .docker-env
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
    entrypoint: bash -c
    command: |
      "bundle install && \
      bundle exec rails s -b 0.0.0.0 -p 3000"
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=expressive-writing_development
    ports:
      - "4306:3306"
