default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  port: 3306

development:
  <<: *default
  username: root
  host: db
  database: expressive-writing_development
  soket: /tmp/mysql.sock

test:
  <<: *default
  username: root
  host: <%= ENV.fetch('DB_HOST', 'db') %>
  database: expressive-writing_test
  soket: /tmp/mysql.sock

production:
  <<: *default
  database: expressive-writing_production
  username: expressive-writing
  password: <%= ENV['EXPRESSIVE-WRITING_DATABASE_PASSWORD'] %>
  