default: &default
  adapter: mysql2
  charset: utf8
  encoding: utf8mb4
  pool: 5
  port: 3306

development:
  <<: *default
  username: root
  host: db
  database: expressive-writing_development
  soket: /tmp/mysql.sock

test:
  <<: *default
  username: root
  host: <%= ENV.fetch('DB_HOST', 'test-db') %>
  database: expressive-writing_test
  soket: /tmp/mysql.sock

production:
  <<: *default
  database: <%= Rails.application.credentials.db[:name] %>
  username: <%= Rails.application.credentials.db[:user] %>
  password: <%= Rails.application.credentials.db[:password] %>
  host: <%= Rails.application.credentials.db[:host] %>
  